### ISSUE TITLE
Add System/files support

### ISSUE THREAD

**Issue by Ladylain** [dev-lav/api-generator#15]
Hi, 

First, i would like to say you thanks for this plugin cause it's a real pleasure. 
Second, i'm trying to create an API for my model but my data have an AttachMany which refers to System/Files (upload). 

i've write this relation 

{ "fillable": "id,name,image" ,"relation": [{ "name": "gallery", "fillable": "id,disk_name" }]}
but the result is : 

`{
"status_code": 200,
"message": "success",
"data": [
{
"id": 1,
"name": "Hotel Le Mottaret",
"image": "/Rooms/cropped-images/XQ7A6799-0-0-0-0-1521716260.jpg",
"gallery": []
},
{
"id": 2,
"name": "Hôtel Ibiza",
"image": "/JD1_6391.jpg",
"gallery": []
}
]
}`

How can i get all my files attach to my data and show their link in the result ? 

thanks

**Comment by dev-lav** [comment]
@Ladylain hmm, I will check it. Sorry for my late reply

**Comment by dev-lav** [comment]
@Ladylain 
I use this custom condition, and it work :)
```json
{
	"fillable": "id,title,content",
	"relation": [{
		"name": "user",
		"fillable": "id,first_name"
	}, {
		"name": "categories",
		"fillable": "id,name"
	}, {
		"name": "featured_images",
		"fillable": ""
	}]
}
```

Model : Rainlab - Blog

**Comment by Ladylain** [comment]
Hello

Thanks for you reply, but i have done my own securised API. And i have all data that i want into. Maybe your reply will help somebody :)
