### ISSUE TITLE
Two endpoints seems not to work

### ISSUE THREAD

**Issue by msouidi309** [dev-lav/api-generator#16]
As-Salamu Alaykum brother, thanks for this plugin, it's awesome !
I just have a question : when i register two endpoints, it doesn't work !
The last created works but the first one doesn't. Is there anything i made wrong ?

**Comment by dev-lav** [comment]
@msouidi309 Wa Alaikum salam brother, can you explain how you register your two endpoints?

**Comment by dev-lav** [comment]
the issue already fix, you check on PR #19
