### ISSUE TITLE
Class AhmadFatoni\ApiGenerator\Controllers\API\blogController does not exist

### ISSUE THREAD

**Issue by ghost** [dev-lav/api-generator#2]
<img src="http://i.imgur.com/cPUpdgp.png">

**Comment by dev-lav** [comment]
please check your folder permission, maybe this plugin failed to create controller file

**Comment by ghost** [comment]
Hi
i have checked the folder
blogController.php is created, but it seems like cant get this controller

**Comment by dev-lav** [comment]
Check file permission, 

Do you already try to make another API ?

**Comment by ghost** [comment]
I got it, there are something wrong with php 7

**Comment by dev-lav** [comment]
have you finished it ?

**Comment by ghost** [comment]
Hi @ran-tw ,

Could you please tell how to fix it with PHP 7?

Thanks a lot
