### ISSUE TITLE
Exception when trying to access a specific blog post

### ISSUE THREAD

**Issue by boris61** [dev-lav/api-generator#20]
Hello,

when I try to access the default endpoint that I created for blog posts (/api/v1/posts) it works fine, lists all blog posts. But if I try to do, for example /api/v1/posts/1 I get an exception with the following 

> count(): Parameter must be an array or an object that implements Countable

`public funtion show($id) {`
  `$data = $this->Post->where('id',$id)->first();`
` if( count($data) > 0){`
`return $this->helpers->apiArrayResponseBuilder(200, 'success', $data);`
`}`

on

> /apigenerator/controllers/api/postController.php line 34

Any help? Thanks

**Comment by dev-lav** [comment]
I have tried at the same model, it works well. Can you explain the problem?

**Comment by frendhisaido** [comment]
@boris61 which php version are you using?
`count(): Parameter must be an array or an object that implements Countable`

> An E_WARNING will now be emitted when attempting to count() non-countable types (this includes the sizeof() alias function).

https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
