### ISSUE TITLE
Cannot make non static method Illuminate\Routing\Controller::getMiddleware() static in class AhmadFatoni\ApiGenerator\Controllers\ApiGeneratorController

### ISSUE THREAD

**Issue by frijj2k** [dev-lav/api-generator#21]
After updating today to the latest October CMS via update in the backend, API Generator no longer works with the error:

```
Cannot make non static method Illuminate\Routing\Controller::getMiddleware() static in class AhmadFatoni\ApiGenerator\Controllers\ApiGeneratorController

In file: <full_path>/plugins/ahmadfatoni/apigenerator/controllers/ApiGeneratorController.php line 336
```

Changing the second to last function in the ApiGeneratorController.php ( getMiddleware() ) to a non-static method fixes the issue. Thought you should be aware.

**Comment by kevinjon27** [comment]
+1. I got this too

**Comment by dev-lav** [comment]
@kevinjon27 @frijj2k I have solved this issue, please update your plugin. Thanks.
